%%
%% Generate 2 * n + 1 symmetric raster line templates. 
%%
%% Each line passes through the center pixel of the matrix, and is offset by
%% one pixel along the top and bottom edge of the EPI, relative to the previous 
%% one. The slope of each line is returned in m.
%%
function [L, m] = genLines(n, epiSz)

  h = epiSz(1) * 2 + 1;
  off = h/epiSz(1);
  w = 2 * ceil(n * off) + 1;
  midw = ceil(w/2);

  L = zeros(h, w, n * 2 - 1);
  m = zeros(1, n * 2 - 1);

  [X, ~] = meshgrid( 1:w, 1:h );

  for i = 1:n
    x = [midw + (n - i) * off midw - (n - i) * off];  
    y = [1 h];  
    nPoints = max(abs(diff(x)), abs(diff(y)) ) + 1;
    rIdx = max(1, min(round(linspace(y(1), y(2), nPoints)), h));  % Row indices
    cIdx = max(1, min(round(linspace(x(1), x(2), nPoints)), w));  % Column indices
    idx = sub2ind([h, w], rIdx, cIdx); 
    L(idx + (i - 1) * w * h) = 1;
    m(i) = h / (2 * (n - i) * off);
  end

  % the next n lines are generated by flipping the existing ones
  L(:, :, n + 1:end) = fliplr( L(:, :, n-1:-1:1));
  m(n + 1:end) = -m(n-1:-1:1);
end

